// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: proto/game-data.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "game_data";

/** ===== COMMON ===== */
export interface Empty {
}

/** ===== MAP BASE ===== */
export interface MapBase {
  id: number;
  ten: string;
}

export interface GetAllMapResponse {
  maps: MapBase[];
}

export interface ThemMapRequest {
  ten: string;
}

export interface SuaMapRequest {
  id: number;
  ten: string;
}

export interface XoaMapRequest {
  id: number;
}

/** ===== NPC BASE ===== */
export interface NpcBase {
  id: number;
  ten: string;
  /** NGUOI, CAYDAU, RUONGDO, DUIGA */
  loai: string;
}

export interface GetAllNpcBaseResponse {
  npcs: NpcBase[];
}

export interface ThemNpcBaseRequest {
  ten: string;
  loai: string;
}

export interface SuaNpcBaseRequest {
  id: number;
  ten: string;
  loai: string;
}

export interface XoaNpcBaseRequest {
  id: number;
}

/** ===== NPC SPAWN ===== */
export interface NpcSpawn {
  id: number;
  npc_base_id: number;
  /** join từ npc_base để client khỏi query thêm */
  ten_npc: string;
  loai_npc: string;
  map_id: number;
  /** join từ map_base */
  ten_map: string;
  x: number;
  y: number;
  is_active: boolean;
}

export interface GetNpcTheoMapRequest {
  map_id: number;
}

export interface GetNpcTheoMapResponse {
  npcs: NpcSpawn[];
}

export interface ThemNpcSpawnRequest {
  npc_base_id: number;
  map_id: number;
  x: number;
  y: number;
  is_active: boolean;
}

export interface SuaNpcSpawnRequest {
  id: number;
  map_id: number;
  x: number;
  y: number;
  is_active: boolean;
}

export interface XoaNpcSpawnRequest {
  id: number;
}

/** ===== NPC SHOP ITEM ===== */
export interface NpcShopItem {
  id: number;
  npc_base_id: number;
  ten_npc: string;
  item_base_id: number;
  /** ← join từ item_base */
  ten_item: string;
  /** ← join từ item_base */
  ma_item: string;
  gia: number;
  loaiTien: string;
  tab: string;
  is_active: boolean;
  /** epoch millis, null = bán ngay */
  start_at?:
    | number
    | undefined;
  /** epoch millis, null = vô thời hạn */
  end_at?: number | undefined;
}

export interface GetShopTheoNpcRequest {
  npc_base_id: number;
}

export interface GetShopTheoNpcResponse {
  items: NpcShopItem[];
}

export interface ThemShopItemRequest {
  npc_base_id: number;
  item_base_id: number;
  gia: number;
  loaiTien: string;
  tab: string;
  is_active?: boolean | undefined;
  start_at?: number | undefined;
  end_at?: number | undefined;
}

export interface SuaShopItemRequest {
  id: number;
  item_base_id?: number | undefined;
  gia?: number | undefined;
  loaiTien?: string | undefined;
  tab?: string | undefined;
  is_active?: boolean | undefined;
  start_at?: number | undefined;
  end_at?: number | undefined;
}

export interface XoaShopItemRequest {
  id: number;
}

export interface XoaShopItemResponse {
  npcId: number;
}

/** ===== ITEM BASE ===== */
export interface ItemBase {
  id: number;
  ten: string;
  ma: string;
}

export interface GetAllItemBaseRequest {
}

export interface GetAllItemBaseResponse {
  items: ItemBase[];
}

export interface ThemItemBaseRequest {
  ten: string;
  ma: string;
}

export interface ThemItemBaseResponse {
  item: ItemBase | undefined;
}

export interface SuaItemBaseRequest {
  id: number;
  ten: string;
  ma: string;
}

export interface SuaItemBaseResponse {
  item: ItemBase | undefined;
}

export interface XoaItemBaseRequest {
  id: number;
}

export const GAME_DATA_PACKAGE_NAME = "game_data";

/** ===== SERVICE DEFINITION ===== */

export interface GameDataServiceClient {
  /** Map base */

  getAllMap(request: Empty, metadata?: Metadata): Observable<GetAllMapResponse>;

  themMap(request: ThemMapRequest, metadata?: Metadata): Observable<MapBase>;

  suaMap(request: SuaMapRequest, metadata?: Metadata): Observable<MapBase>;

  xoaMap(request: XoaMapRequest, metadata?: Metadata): Observable<Empty>;

  getNpcTheoMap(request: GetNpcTheoMapRequest, metadata?: Metadata): Observable<GetNpcTheoMapResponse>;

  /** Npc base */

  getAllNpcBase(request: Empty, metadata?: Metadata): Observable<GetAllNpcBaseResponse>;

  themNpcBase(request: ThemNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  suaNpcBase(request: SuaNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  xoaNpcBase(request: XoaNpcBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc spawn */

  themNpcSpawn(request: ThemNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  suaNpcSpawn(request: SuaNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  xoaNpcSpawn(request: XoaNpcSpawnRequest, metadata?: Metadata): Observable<Empty>;

  /** Item base */

  getAllItemBase(request: GetAllItemBaseRequest, metadata?: Metadata): Observable<GetAllItemBaseResponse>;

  themItemBase(request: ThemItemBaseRequest, metadata?: Metadata): Observable<ThemItemBaseResponse>;

  suaItemBase(request: SuaItemBaseRequest, metadata?: Metadata): Observable<SuaItemBaseResponse>;

  xoaItemBase(request: XoaItemBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc shop item */

  getShopTheoNpc(request: GetShopTheoNpcRequest, metadata?: Metadata): Observable<GetShopTheoNpcResponse>;

  themShopItem(request: ThemShopItemRequest, metadata?: Metadata): Observable<NpcShopItem>;

  suaShopItem(request: SuaShopItemRequest, metadata?: Metadata): Observable<NpcShopItem>;

  xoaShopItem(request: XoaShopItemRequest, metadata?: Metadata): Observable<XoaShopItemResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface GameDataServiceController {
  /** Map base */

  getAllMap(request: Empty, metadata?: Metadata): Observable<GetAllMapResponse>;

  themMap(request: ThemMapRequest, metadata?: Metadata): Observable<MapBase>;

  suaMap(request: SuaMapRequest, metadata?: Metadata): Observable<MapBase>;

  xoaMap(request: XoaMapRequest, metadata?: Metadata): Observable<Empty>;

  getNpcTheoMap(request: GetNpcTheoMapRequest, metadata?: Metadata): Observable<GetNpcTheoMapResponse>;

  /** Npc base */

  getAllNpcBase(request: Empty, metadata?: Metadata): Observable<GetAllNpcBaseResponse>;

  themNpcBase(request: ThemNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  suaNpcBase(request: SuaNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  xoaNpcBase(request: XoaNpcBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc spawn */

  themNpcSpawn(request: ThemNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  suaNpcSpawn(request: SuaNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  xoaNpcSpawn(request: XoaNpcSpawnRequest, metadata?: Metadata): Observable<Empty>;

  /** Item base */

  getAllItemBase(request: GetAllItemBaseRequest, metadata?: Metadata): Observable<GetAllItemBaseResponse>;

  themItemBase(request: ThemItemBaseRequest, metadata?: Metadata): Observable<ThemItemBaseResponse>;

  suaItemBase(request: SuaItemBaseRequest, metadata?: Metadata): Observable<SuaItemBaseResponse>;

  xoaItemBase(request: XoaItemBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc shop item */

  getShopTheoNpc(request: GetShopTheoNpcRequest, metadata?: Metadata): Observable<GetShopTheoNpcResponse>;

  themShopItem(request: ThemShopItemRequest, metadata?: Metadata): Observable<NpcShopItem>;

  suaShopItem(request: SuaShopItemRequest, metadata?: Metadata): Observable<NpcShopItem>;

  xoaShopItem(request: XoaShopItemRequest, metadata?: Metadata): Observable<XoaShopItemResponse>;
}

export function GameDataServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAllMap",
      "themMap",
      "suaMap",
      "xoaMap",
      "getNpcTheoMap",
      "getAllNpcBase",
      "themNpcBase",
      "suaNpcBase",
      "xoaNpcBase",
      "themNpcSpawn",
      "suaNpcSpawn",
      "xoaNpcSpawn",
      "getAllItemBase",
      "themItemBase",
      "suaItemBase",
      "xoaItemBase",
      "getShopTheoNpc",
      "themShopItem",
      "suaShopItem",
      "xoaShopItem",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GameDataService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GameDataService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GAME_DATA_SERVICE_NAME = "GameDataService";
